### ISSUE TITLE
4D v13 Mac Plugin not working

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-curl#1]
Hi Keisuke,

it seems that the plugin part (v11 folder) is missing one file inside Resources

![bildschirmfoto 2016-08-04 um 15 49 39](https://cloud.githubusercontent.com/assets/6436037/17404341/9ccc033c-5a5b-11e6-8063-a25aa7450a1d.png)
![bildschirmfoto 2016-08-04 um 15 49 26](https://cloud.githubusercontent.com/assets/6436037/17404340/9cc8c208-5a5b-11e6-8b14-0c0c672ba8e3.png)

Regards
Armin

**Comment by miyako** [comment]
please check again with latest version
