### ISSUE TITLE
How to use FTPS?

### ISSUE THREAD

**Issue by christianschneider89** [miyako/4d-plugin-curl#2]
Hello

Can you give me a example for using FTPS with your plugin?
I need to up- and download files.

Thanks!

Chris

**Comment by miyako** [comment]
I think you just need to use a URL that starts with ``ftps://``

**Comment by miyako** [comment]
try google ``libcurl`` ``ftps`` 

``ftp://`` means you start plain text and switch to TLS as opposed to ``ftps://`` which is TLS from the start.

**Comment by christianschneider89** [comment]
Ok, thanks. I got it with much googling ;-)
