### ISSUE TITLE
4D Crash on Mac OS 10.12.4+

### ISSUE THREAD

**Issue by christianschneider89** [miyako/4d-plugin-curl#3]
When we copy the plugin into the 4D Server Plugin Folder and we start die 4D Client Application on Mac OS 10.12.4+ 4D crashes after the login screen with following error:

```
Process:               4D [992]
Path:                  /Applications/4D_V13.6/4D.app/Contents/MacOS/4D
Identifier:            com.4d.4d
Version:               13.6 [186703] (186703)
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           4D [992]
User ID:               501

Date/Time:             2017-12-13 09:18:13.018 +0100
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        E278EFAC-5E36-349E-1C60-31A2B2240265


Time Awake Since Boot: 260 seconds

System Integrity Protection: enabled

Crashed Thread:        12  Anwendungsprozess

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]
```

- We use 4D V13.6.
- 4D crashes before "On Startup" method.
- Up to Mac OS 10.12.3 it works perfect, also on windows 10.
- We have not tested it on Mac OS 10.13.

Chris

**Comment by miyako** [comment]
thanks for sharing. 

as the project is completely open source, you could either try to fix it yourself, find someone who can do it for you, or contact us at Info-JP@4D.com and request a quote for studying and fixing the issue.

I am sure our sales people can offer a reasonable pricing.

**Comment by christianschneider89** [comment]
Ok, we will try it with 4D V16, I hope this will work on Mac OS 10.12.4+

**Comment by miyako** [comment]
you are right, it would be interesting to test whether:

the problem also happens on a newer version of 4D
the problem is not a side-effect of installing several different plugins.
