### ISSUE TITLE
4D v16r6 64 win shows Runtime error code 126 () at start

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-curl#4]
Testing the curl demo plugin with v16r6 64 build 220943 shows an error dialog after opening the demo database

Windows 10
![2018-02-28 16_51_29-runtime error](https://user-images.githubusercontent.com/6436037/36797209-aef56e3a-1ca7-11e8-8093-64f1b683ebf2.png)

Runtime Error code 126 () 

Regards Armin

**Comment by miyako** [comment]
I don't reproduce the problem Windows 10 1709, 16R6.220943 64-bit

**Comment by balzercomp** [comment]
Hi Keisuke, I'm facing the same problem in our database. I narrowed it down to the curl and pdftk components I'm using. If I remember correctly, we had some similar problems before. They were related to a dll that is used with the Japanese OS, but is no present in international versions. I get the error Armin describes with win srv 2008r2 64bit and the release version of 4d 16r6 server as well as single user. Without pdftk.4dbase and cURL.callback.4dbase in the components folder, the error disappears. As soon as I put any of them back in, the error reappears. It would be very appreciated if you could provide us with a version that doesn't throw that error.

Thanks for your very good work and you kind assistance

Gerald

**Comment by balzercomp** [comment]
I found the solution. The problem is related to the database language of the components being set to Japanese. After switching it to English the error is gone. Probably any other roman character Language will work too.

Thanks again

Gerald
