### ISSUE TITLE
Crash on windows 64 bits / 4Dv15 R5

### ISSUE THREAD

**Issue by weshprod** [miyako/4d-plugin-curl#5]
Hi,
I've downloaded the latest version but it seems to crash on Windows 64 Bits. Mac is fine

<img width="333" alt="Screen Shot 2019-03-15 at 17 39 05" src="https://user-images.githubusercontent.com/16133754/54447601-1f500280-474a-11e9-843b-896117335986.png">

**Comment by miyako** [comment]
this plugin is obsolete. please consider v2 (the syntax is different but the code is maintained)

https://github.com/miyako/4d-plugin-curl-v2
