### ISSUE TITLE
"cURL and cURL FTP are damaged" Mac OS Catalina

### ISSUE THREAD

**Issue by djbeckett** [miyako/4d-plugin-curl#6]
4D 17.4 on Mac OS Catalina says that cURL and cURL FTP are damaged and can't be used. Is it possible to fix this so they will work? Thank you!

**Comment by miyako** [comment]
can you please explain where (the exact URL) you downloaded the plugin and how you installed it in your application?

**Comment by miyako** [comment]
also, is there a reason for not using 

https://github.com/miyako/4d-plugin-curl-v2

I decided there is no value in this branch except for supporting old 4D (v13 or thereabouts).

**Comment by djbeckett** [comment]
I apologize for not providing all the details. I also was not aware of the newer version. I will try the newer version and let you know if I’m still having trouble.
